media:
  input: public/assets/uploads
  output: /assets/uploads
  categories: [image]

components:
  button:
    type: object
    label: Button
    fields:
      - name: title
        label: Text
        type: string
      - name: href
        label: Link
        type: string
      - name: type
        label: Style
        type: select
        options:
          values: [primary, secondary]

  section:
    type: object
    label: Section
    fields:
      - name: type
        label: Section type
        type: select
        options:
          values: [hero, default]
      - name: cols
        label: Columns
        type: select
        options:
          values: [1, 2, 3, 4, 5]
      - name: blocks
        label: Content blocks
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{heading} ({index})"
        fields:
          - name: heading
            label: Heading
            type: string
          - name: text
            label: Text
            type: rich-text
          - name: image
            label: Image
            type: object
            fields:
              - name: src
                label: File
                type: image
              - name: alt
                label: Alternative text
                type: string
          - name: button
            component: button

content:
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    format: yaml-frontmatter
    exclude:
      - index.astro
      - "[slug].astro"
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title]
    fields:
      - name: layout
        label: Layout
        type: string
        default: ../layouts/ContentLayout.astro
        hidden: true
        readonly: true
      - name: title
        label: Page title
        type: string
        required: true
      - name: sections
        label: Page sections
        component: section
        list:
          collapsible:
            collapsed: true
            summary: "{type} ({index})"

settings:
  content:
    merge: true
